title: Porsche Collector's Blog
author: dinotom
email: carcollectordata@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is dedicated to providing the most complete sales data on the collectibility and value forecasting for collectible, rare, loved Porsche models.

# social links
twitter_username: carcollectordata # DO NOT include the @ character, or else the build will fail!
github_username:  dinotom # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
