title: Porsche Collector's Blog
theme: minima
author: dinotom
email: carcollectordata@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The most extensive collector data for highly sought after Porsche models

# social links
twitter_username: carcollectordata # DO NOT include the @ character, or else the build will fail!
github_username:  dinotom # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
